### ISSUE TITLE
跑样例提示 window.luckysheet.destroy is not a function

### ISSUE THREAD

**Issue by 2016011969sunyifang** [hjwforever/luckysheet-vue3-vite#1]
window.luckysheet.destroy is not a function
 不太清楚什么原因 麻烦看下
 
![image](https://user-images.githubusercontent.com/37146715/172975329-908602bc-c49e-427c-98e7-7483c82fd382.png)

**Comment by jwhx** [comment]
我这测试不出来。
目前强行修复了，可以测试下。
如果还有报错的话，可以提供复现方法。

**Comment by moogy1** [comment]
> window.luckysheet.destroy is not a function 不太清楚什么原因 麻烦看下
> 
> ![image](https://user-images.githubusercontent.com/37146715/172975329-908602bc-c49e-427c-98e7-7483c82fd382.png)

同样的报错 请问解决了么

**Comment by jwhx** [comment]
> > window.luckysheet.destroy is not a function 不太清楚什么原因 麻烦看下
> > ![image](https://user-images.githubusercontent.com/37146715/172975329-908602bc-c49e-427c-98e7-7483c82fd382.png)
> 
> 同样的报错 请问解决了么

我又更新了一下，并且本地跑起来测试也没有报错。
@moogy1 你可以更新一下，如果还报错的话，可以提供复现的例子。
