### ISSUE TITLE
Luckysheet error with Spectrum

### ISSUE THREAD

**Issue by giuliaSan** [hjwforever/luckysheet-vue3-vite#2]
When trying to use the color pickers
**menuButton.js:573 Uncaught TypeError: $(...).find(...).spectrum is not a function**

Using luckysheet + luckyexcel (vue3)

**Comment by jwhx** [comment]
> When trying to use the color pickers **menuButton.js:573 Uncaught TypeError: $(...).find(...).spectrum is not a function**
> 
> Using luckysheet + luckyexcel (vue3)

Can you give a [minimal reproduction](https://stackoverflow.com/help/minimal-reproducible-example) ？
